// Generates contracts/test/fixtures/airdrop-shapes.json.
//
// The JS tree and OpenZeppelin's MerkleProof have to agree at every tree
// SHAPE, not just on one example. The interesting shapes are the ones where a
// layer has odd length — the last node is promoted unpaired, and a promotion
// that the two implementations disagree about produces proofs that verify in
// JS and revert on chain. Sizes with TWO or more odd layers are the ones worth
// having, because they promote twice.
//
//   node tools/test/airdrop-shapes.mjs
//
// Kept small on purpose: the Solidity side re-parses this file for every leaf,
// and the first version of it (every size 1..40, ~387KB) ran the test out of
// gas at a billion units. Coverage comes from picking the awkward shapes, not
// from picking all of them.
import { writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getAddress } from 'viem';
import { leafOf, buildTree, proofFor } from '../airdrop-snapshot.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

// 1 and 2 are the degenerate cases. 3,5,7,9,11 promote once. 13,23,29 promote
// on more than one layer. 16 and 32 are the perfectly balanced controls.
const SIZES = [1, 2, 3, 5, 7, 9, 11, 13, 16, 23, 29, 32];

const trees = SIZES.map((n) => {
  const rows = Array.from({ length: n }, (_, i) => ({
    address: getAddress('0x' + (i + 1).toString(16).padStart(40, '0')),
    amount: BigInt(i + 1) * 10n ** 15n,
  }));
  const leaves = rows.map((r, i) => leafOf(i, r.address, r.amount));
  const layers = buildTree(leaves);
  return {
    n,
    root: layers[layers.length - 1][0],
    accounts: rows.map((r) => r.address),
    amounts: rows.map((r) => '0x' + r.amount.toString(16)),
    proofs: rows.map((_, i) => proofFor(layers, i)),
    layerSizes: layers.map((l) => l.length),
  };
});

await mkdir(join(ROOT, 'contracts/test/fixtures'), { recursive: true });
await writeFile(
  join(ROOT, 'contracts/test/fixtures/airdrop-shapes.json'),
  JSON.stringify({ note: 'Generated by tools/test/airdrop-shapes.mjs', trees }, null, 1),
);

for (const t of trees) {
  const odd = t.layerSizes.filter((s) => s % 2 === 1 && s > 1).length;
  console.log(`n=${String(t.n).padStart(2)}  layers ${t.layerSizes.join(',').padEnd(18)} odd layers ${odd}`);
}
