/* GENERATED by tools/index-memes.mjs — do not edit by hand.
   Drop art into assets/memes/, run the script, commit. */
window.KEVIN_MEMES = [
  {
    "file": "kevins-gym.png",
    "title": "Kevins Gym",
    "w": 1600,
    "h": 900
  },
  {
    "file": "the-getaway.png",
    "title": "The Getaway",
    "w": 1600,
    "h": 900
  },
  {
    "file": "told-no-stayed-anyway.png",
    "title": "Told No Stayed Anyway",
    "w": 1600,
    "h": 900
  }
];
