// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {MerkleProof} from "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";

/// @dev verifyCalldata needs calldata, so the proof has to arrive through an
///      external call rather than from memory in the test itself.
contract Verifier {
    function verify(bytes32[] calldata proof, bytes32 root, bytes32 leaf) external pure returns (bool) {
        return MerkleProof.verifyCalldata(proof, root, leaf);
    }
}

/**
 * The JS tree builder and OpenZeppelin's verifier have to agree at every tree
 * SHAPE, not merely on one example.
 *
 * The shapes that matter are the ones with an odd-length layer: the last node
 * is promoted unpaired, and if the two implementations disagreed about that
 * promotion the proofs would verify in JS and revert on chain — after the
 * tokens had been sent. contracts/test/fixtures/airdrop-shapes.json therefore
 * carries sizes that promote on nought, one, two and three layers, with 16 and
 * 32 as perfectly balanced controls.
 *
 * Generated by tools/test/airdrop-shapes.mjs, which prints the layer sizes so
 * you can see which shapes are actually being exercised.
 */
contract AirdropShapesTest is Test {
    Verifier internal ver;
    string internal json;
    uint256 internal constant SHAPES = 12;

    function setUp() public {
        ver = new Verifier();
        json = vm.readFile("test/fixtures/airdrop-shapes.json");
    }

    function _leaf(uint256 i, address a, uint256 amt) internal pure returns (bytes32) {
        return keccak256(bytes.concat(keccak256(abi.encode(i, a, amt))));
    }

    /// @dev Every proof the JS builder emits verifies under OpenZeppelin.
    function test_everyShapeAgreesWithOpenZeppelin() public view {
        for (uint256 t = 0; t < SHAPES; t++) {
            string memory p = string.concat(".trees[", vm.toString(t), "]");
            bytes32 root = vm.parseJsonBytes32(json, string.concat(p, ".root"));
            address[] memory who = vm.parseJsonAddressArray(json, string.concat(p, ".accounts"));
            uint256[] memory amt = vm.parseJsonUintArray(json, string.concat(p, ".amounts"));
            for (uint256 i = 0; i < who.length; i++) {
                bytes32[] memory proof =
                    vm.parseJsonBytes32Array(json, string.concat(p, ".proofs[", vm.toString(i), "]"));
                assertTrue(
                    ver.verify(proof, root, _leaf(i, who[i], amt[i])),
                    string.concat("n=", vm.toString(who.length), " leaf ", vm.toString(i))
                );
            }
        }
    }

    /// @dev And a proof for one leaf never verifies another. Checked on the
    ///      small trees only: it is quadratic, and the promotion behaviour it
    ///      is guarding is fully exercised by n=3,5,7,9.
    function test_oneLeafsProofNeverVerifiesAnother() public view {
        for (uint256 t = 0; t < 6; t++) {
            string memory p = string.concat(".trees[", vm.toString(t), "]");
            bytes32 root = vm.parseJsonBytes32(json, string.concat(p, ".root"));
            address[] memory who = vm.parseJsonAddressArray(json, string.concat(p, ".accounts"));
            uint256[] memory amt = vm.parseJsonUintArray(json, string.concat(p, ".amounts"));
            if (who.length < 2) continue;
            for (uint256 i = 0; i < who.length; i++) {
                bytes32[] memory proof =
                    vm.parseJsonBytes32Array(json, string.concat(p, ".proofs[", vm.toString(i), "]"));
                for (uint256 j = 0; j < who.length; j++) {
                    if (i == j) continue;
                    assertFalse(
                        ver.verify(proof, root, _leaf(j, who[j], amt[j])),
                        string.concat("n=", vm.toString(who.length), " proof ", vm.toString(i))
                    );
                }
            }
        }
    }
}
