#!/usr/bin/env node
// Scans assets/memes/ and writes js/memes-data.js.
//
// Adding a meme is: drop the file in assets/memes/, run this, commit.
// Filenames become titles — "robinhood-cereal.png" -> "Robinhood Cereal" —
// so name files properly and you never touch a config by hand.
//
//   node tools/index-memes.mjs
//
import { readdir, writeFile, readFile } from 'node:fs/promises';
import { join, dirname, extname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(ROOT, 'assets/memes');
const OUT = join(ROOT, 'js/memes-data.js');
const OK = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif']);

const titleFrom = (file) =>
  basename(file, extname(file))
    .replace(/[-_]+/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase())
    .trim();

/** Pull intrinsic dimensions so the grid can reserve space and not jump. */
async function dimensions(path) {
  const buf = await readFile(path);
  if (buf.slice(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))) {
    return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
  }
  if (buf[0] === 0xff && buf[1] === 0xd8) {
    let i = 2;
    while (i < buf.length - 9) {
      if (buf[i] !== 0xff) { i++; continue; }
      const marker = buf[i + 1];
      const len = buf.readUInt16BE(i + 2);
      if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
        return { h: buf.readUInt16BE(i + 5), w: buf.readUInt16BE(i + 7) };
      }
      i += 2 + len;
    }
  }
  if (buf.slice(0, 4).toString() === 'RIFF' && buf.slice(8, 12).toString() === 'WEBP') {
    const t = buf.slice(12, 16).toString();
    if (t === 'VP8X') return { w: (buf.readUIntLE(24, 3) & 0xffffff) + 1, h: (buf.readUIntLE(27, 3) & 0xffffff) + 1 };
  }
  if (buf.slice(0, 3).toString() === 'GIF') return { w: buf.readUInt16LE(6), h: buf.readUInt16LE(8) };
  return { w: 1600, h: 900 };
}

async function main() {
  let files = [];
  try {
    files = (await readdir(DIR)).filter((f) => OK.has(extname(f).toLowerCase())).sort();
  } catch {
    // folder not there yet — that's fine, we write an empty manifest
  }

  const items = [];
  for (const f of files) {
    const { w, h } = await dimensions(join(DIR, f));
    items.push({ file: f, title: titleFrom(f), w, h });
  }

  const body =
    `/* GENERATED by tools/index-memes.mjs — do not edit by hand.\n` +
    `   Drop art into assets/memes/, run the script, commit. */\n` +
    `window.KEVIN_MEMES = ${JSON.stringify(items, null, 2)};\n`;

  await writeFile(OUT, body);
  console.log(`indexed ${items.length} meme${items.length === 1 ? '' : 's'} -> js/memes-data.js`);
  for (const i of items) console.log(`   ${i.title}  (${i.w}x${i.h})`);
  if (!items.length) console.log('   assets/memes/ is empty — drop art in and run this again.');
}

await main();
